### ISSUE TITLE
my_coin_send() function is rubbish

### ISSUE THREAD

**Issue by NET-OF-BEING** [clugg/coinspot-py#2]
The my_coin_send function supposedly is meant to send x amount of crypto to the given input address, however, according to the coinspot API, no such POST url exists (/my/coin/send) and there is no function within the SDK for sending crypto to another address. I decided to investigate this after repeatedly receiving errors saying my api key is not valid and so I'm not sure why this magical function is here at all. Is this maybe a deprecated API request url?

def my_coin_send(self, cointype, address, amount):
        return self._request("my/coin/send", {
            "cointype": cointype,
            "address": address,
            "amount": amount
        })

**Comment by clugg** [comment]
You are correct - I haven't updated this in about 3 years (and honestly haven't used CoinSpot in that time either). Happy to accept a PR for this, or I will look into updating the library to reflect the new API endpoints soon.

**Comment by NET-OF-BEING** [comment]
I'm  not sure there are endpoints for allowing withdraw of crypto to external addresses with Coinspot API. I'm not sure this exchange want users to use they're platform as though it is designed for fast trading...

**Comment by NET-OF-BEING** [comment]
someone should update the API if possible to allow users to send coins to other addresses.
